version: "3.0"

services: 
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/backend
      - /backend/node_modules
    ports:
      - 5000:5000
    depends_on:
      - postgres
    restart: always
    


  postgres:
    container_name: postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always


volumes:
  pgdata: